# this is a conda environment definition file
name: gv
channels:
  - defaults
dependencies:
  - pip
  - python=3.9
  - pip:
      - cached_property
      - gym
      - imageio
      - imageio-ffmpeg
      - more_itertools
      - numpy
      - pyyaml
      - schema
      - termcolor
      - typing-extensions
      # dev
      - Sphinx==3.3.1
      - black==20.8b1
      - bump2version==1.0.1
      - coverage==5.3
      - flake8==3.8.4
      - ipdb==0.13.4
      - isort==5.6.4
      - mypy==0.800
      - pytest==6.1.2
      - sphinx-theme==1.0
      - sphinxcontrib-napoleon==0.7
      - tox==3.20.1
      - twine==3.2.0
      - watchdog==0.10.3
