[tool.black]
skip_string_normalization = true
line_length = 80

[tool.isort]  # black compatibility
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
combine_as_imports = true
line_length = 80

[tool.pylint.messages_control]  # black compatibility
disable = "C0330,C0326"
max_line_length = 80
